#!/usr/bin/env bash
# Untracks build artifacts, local databases, generated pentest reports,
# and scratch test files that were accidentally committed. Files stay on
# disk — this only removes them from git tracking. Run from repo root.
set -e

git rm -r --cached --quiet \
  "Saga-ai/Aegis-AI/aegis_chroma_db/aegis_history.db" \
  "Saga-ai/Aegis-AI/aegis_chroma_db/chroma.sqlite3" \
  "Saga-ai/Aegis-AI/src/__pycache__/analyzer.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/cli.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/critic.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/database.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/main.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/memory.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/recon.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/reporter.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/sca.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/scanner.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/swarm.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/__pycache__/validator.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/agents/__pycache__/analyzer.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/agents/__pycache__/exploit_runner.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/agents/__pycache__/hypothesis.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/agents/__pycache__/patch_validator.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/agents/__pycache__/prompts.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/agents/__pycache__/recon.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/agents/__pycache__/remediation_planner.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/core/__pycache__/config.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/core/__pycache__/database.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/core/__pycache__/memory.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/orchestrator/__pycache__/graph.cpython-313.pyc" \
  "Saga-ai/Aegis-AI/src/orchestrator/__pycache__/swarm.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/frontend/public/Nexus_GRC_Report_20260621_124738_scan68.html" \
  "Saga-ai/Mini-Mythos/frontend/public/Nexus_GRC_Report_20260621_125743_scan69.html" \
  "Saga-ai/Mini-Mythos/frontend/public/Nexus_GRC_Report_20260621_130435_scan70.html" \
  "Saga-ai/Mini-Mythos/frontend/public/Nexus_GRC_Report_20260621_135637_scan71.html" \
  "Saga-ai/Mini-Mythos/frontend/public/Nexus_GRC_Report_20260719_183337_scan72.html" \
  "Saga-ai/Mini-Mythos/frontend/public/Nexus_GRC_Report_20260719_183346_scan73.html" \
  "Saga-ai/Mini-Mythos/frontend/public/Nexus_GRC_Report_20260719_183746_scan74.html" \
  "Saga-ai/Mini-Mythos/nexus_enterprise.db" \
  "Saga-ai/Mini-Mythos/recon_output.json" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_155155.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_155734.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_214127.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_214742.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_215247.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_220824.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_221847.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260601_222918.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260620_204635.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260620_224923.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260620_225649.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260620_225742.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260621_124738_scan68.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260621_125743_scan69.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260621_130435_scan70.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260621_135637_scan71.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260719_183337_scan72.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260719_183346_scan73.html" \
  "Saga-ai/Mini-Mythos/src/Nexus_GRC_Report_20260719_183746_scan74.html" \
  "Saga-ai/Mini-Mythos/src/__pycache__/main.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/__pycache__/mcp_server.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/__init__.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/exploit_runner.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/grc_reporter.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/hypothesis.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/msf_orchestrator.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/playwright_utils.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/prompts.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/recon.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/agents/__pycache__/recon_agent.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/__init__.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/auth.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/config.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/database.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/findings_store.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/log_streamer.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/logger.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/mcp_client.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/core/__pycache__/memory.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/mythos_db/chroma.sqlite3" \
  "Saga-ai/Mini-Mythos/src/mythos_db/e7772394-178e-4e21-ac52-198dcd646092/data_level0.bin" \
  "Saga-ai/Mini-Mythos/src/mythos_db/e7772394-178e-4e21-ac52-198dcd646092/header.bin" \
  "Saga-ai/Mini-Mythos/src/mythos_db/e7772394-178e-4e21-ac52-198dcd646092/length.bin" \
  "Saga-ai/Mini-Mythos/src/mythos_db/e7772394-178e-4e21-ac52-198dcd646092/link_lists.bin" \
  "Saga-ai/Mini-Mythos/src/nexus_enterprise.db" \
  "Saga-ai/Mini-Mythos/src/orchestrator/__pycache__/__init__.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/orchestrator/__pycache__/graph.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/orchestrator/__pycache__/mcp_orchestrator.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/src/recon_output.json" \
  "Saga-ai/Mini-Mythos/src/tools/__pycache__/nuclei_wrapper.cpython-313.pyc" \
  "Saga-ai/Mini-Mythos/test.py" \
  "Saga-ai/Mini-Mythos/test2.py" \
  "Saga-ai/Mini-Mythos/test3.py" \
  "Saga-ai/aegis_chroma_db/3f73ca6e-4850-4d9f-8ec5-85fad0f50380/data_level0.bin" \
  "Saga-ai/aegis_chroma_db/3f73ca6e-4850-4d9f-8ec5-85fad0f50380/header.bin" \
  "Saga-ai/aegis_chroma_db/3f73ca6e-4850-4d9f-8ec5-85fad0f50380/length.bin" \
  "Saga-ai/aegis_chroma_db/3f73ca6e-4850-4d9f-8ec5-85fad0f50380/link_lists.bin" \
  "Saga-ai/aegis_chroma_db/aegis_history.db" \
  "Saga-ai/aegis_chroma_db/chroma.sqlite3" \
  "Saga-ai/aegis_history.db" \
  "Saga-ai/mcp_servers/github_mcp/__pycache__/server.cpython-313.pyc" \
  "Saga-ai/mcp_servers/msf_nuclei_mcp/__pycache__/server.cpython-313.pyc" \
  "Saga-ai/mcp_servers/sqlite_mcp/__pycache__/server.cpython-313.pyc" \
  "Saga-ai/mythos_db/chroma.sqlite3" \
  "Saga-ai/nexus_enterprise.db" \
  "Saga-ai/tests/__pycache__/test_async_scanner.cpython-313.pyc" \
  "Saga-ai/tests/__pycache__/test_database.cpython-313.pyc" \
  "Saga-ai/tests/__pycache__/test_sca.cpython-313.pyc" \
  "Saga-ai/tests/__pycache__/test_scanner.cpython-313.pyc" \
  "Saga-ai/tests/__pycache__/test_swarm.cpython-313.pyc" \
  "Saga-ai/tests/junk.js" \
  "backend/__pycache__/analysis.cpython-311.pyc" \
  "backend/__pycache__/auth.cpython-311.pyc" \
  "backend/__pycache__/database.cpython-311.pyc" \
  "backend/__pycache__/evidence.cpython-311.pyc" \
  "backend/__pycache__/main.cpython-311.pyc" \
  "backend/__pycache__/models.cpython-311.pyc" \
  "backend/__pycache__/orchestrator.cpython-311.pyc" \
  "backend/__pycache__/report_generator.cpython-311.pyc" \
  "backend/__pycache__/worker.cpython-311.pyc" \
  "backend/alembic/__pycache__/env.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/550b6e8a1bdb_add_started_at_to_scan.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/92084d1019a0_add_mission_and_evidence.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/9e64a7fe8def_update_user.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/b5a94e574c9b_v2_multi_tenant_organization_schema.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/c1b2c3d4e5f6_add_pgvector_and_scan_embeddings.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/d2c3d4e5f6g7_add_response_actions.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/e3d4e5f6g7h8_add_scheduled_scans.cpython-311.pyc" \
  "backend/alembic/versions/__pycache__/eafcf39e4218_add_confidence_score.cpython-311.pyc" \
  "backend/engine/__pycache__/browser_plugin.cpython-311.pyc" \
  "backend/engine/__pycache__/certificate_plugin.cpython-311.pyc" \
  "backend/engine/__pycache__/generic_plugin.cpython-311.pyc" \
  "backend/engine/__pycache__/nmap_plugin.cpython-311.pyc" \
  "backend/engine/__pycache__/plugin_base.cpython-311.pyc" \
  "backend/engine/__pycache__/response.cpython-311.pyc" \
  "backend/engine/__pycache__/subdomain_plugin.cpython-311.pyc" \
  "backend/intelligence/__pycache__/agents.cpython-311.pyc" \
  "backend/intelligence/__pycache__/graph.cpython-311.pyc" \
  "backend/intelligence/__pycache__/threat_intel.cpython-311.pyc" \
  "backend/observability/__pycache__/__init__.cpython-311.pyc" \
  "backend/observability/__pycache__/logger.cpython-311.pyc" \
  "backend/observability/__pycache__/metrics.cpython-311.pyc"

echo "Untracked ${#files[@]} files. Review with 'git status', then commit."
